module.exports = {
	ErrorMessages: [
		"",
		"{newEmbed:{description:❌ | Errors Have Occured!\nIf this error keeps repeating, you should report it immediately in our Support Server. Click the button below.}{color:FF1010}}{delete:10s}{deletecommand}",
		"{actionRow:{button:Support Server:link:https#COLON#//dsc.gg/peppashoppe:false:🎫}{button:Delete:danger:deleteEmbed:false:🗑}}"
	],
	Prefixes: [
		"$getGuildVar[prefix;$guildID;server]",
		"peppa",
		"<@$clientID>",
		"<@!$clientID>"
	],
	Intents: [
		"MessageContent",
		"Guilds",
		"GuildMembers",
		"GuildBans",
		"GuildIntegrations",
		"GuildInvites",
		"GuildVoiceStates",
		"GuildPresences",
		"GuildMessages",
		"GuildMessageReactions",
		"GuildMessageTyping",
		"GuildEmojisAndStickers"
	],
	Tables: ["server", "user", "bot", "message", "chnnls"],
	Caches: [
		"guilds",
		"messages",
		"channels",
		"users",
		"applicationCommands",
		"applicationCommandPermissions",
		"permissionRverwrites",
		"presences",
		"reactions",
		"reactionUsers",
		"roles",
		"stageInstances",
		// "threads",
		// "threadMembers",
		"guildApplicationCommand",
		"guildBans",
		"guildChannels",
		"guildEmojis",
		"guildEmojiRoles",
		"guildInvites",
		"guildMembers",
		"guildMemberRoles",
		"guildStickers"
	],
	Events: [
		"onMessage",
		"onMessageDelete",
		"onMessageUpdate",
		"onMessageDeleteBulk",
		"onGuildJoin",
		"onGuildLeave",
		"onGuildUpdate",
		"onGuildUnavailable",
		"onRoleCreate",
		"onRoleUpdate",
		"onRoleDelete",
		"onChannelCreate",
		"onChannelUpdate",
		"onChannelDelete",
		"onChannelPinsUpdate",
		"onStageInstanceCreate",
		"onStageInstanceUpdate",
		"onStageInstanceDelete",
		"onThreadCreate",
		"onThreadUpdate",
		"onThreadDelete",
		"onThreadListSync",
		"onThreadMemberUpdate",
		"onThreadMembersUpdate",
		"onJoin",
		"onLeave",
		"onMemberUpdate",
		"onMemberAvailable",
		"onMembersChunk",
		"onEmojiCreate",
		"onEmojiDelete",
		"onEmojiUpdate",
		"onStickerCreate",
		"onStickerDelete",
		"onStickerUpdate",
		"onBanAdd",
		"onBanRemove",
		"onReactionAdd",
		"onReactionRemove",
		"onReactionRemoveAll",
		"onReactionRemoveEmoji",
		"onVoiceStateUpdate",
		"onPresenceUpdate",
		"onTypingStart",
		"onInteractionCreate",
		"onApplicationCmdPermsUpdate",
		"onUserUpdate",
		"onVariableCreate",
		"onVariableDelete",
		"onVariableUpdate",
		"onFunctionError",
		// "onWebhookUpdate"
	]
};